"modelinfo":
  "b": "pihl"
  "c": "CRDC Batch 2"
  "e": "CRDC Search"
  "g": "1.0"
  "k": "Node"
  "p": "Property"
"scriptinfo":
  "propsfile": "CRDCProps.yml"
  "modelfile": "CRDC.yml"
  "outputfile": "ConfigOutput.csv"