"modelinfo":
  "Batch User": "pihl"
  "Batch Name": "CDS Batch 1"
  "Model Name": "CDS"
  "Model Version": "1.3"
  "Element Type": "Attributes"
"scriptinfo":
  "propsfile": "CRDCProps.yml"
  "modelfile": "CRDC.yml"
  "outputfile": "ConfigOutput.csv"