"modelinfo":
  "b": "pihl"
  "c": "CDS Batch 1"
  "e": "CDS"
  "g": "1.0"
  "k": "Node"
  "p": "Property"
"mdffiles":
  - 'C:\Users\pihltd\Documents\modeltest\cds-model-props.yml'
  - 'C:\Users\pihltd\Documents\modeltest\cds-model.yml'
"outputfile": 'C:\Users\pihltd\Documents\modeltest\ConfigOutput.csv'
"scriptinfo":
  "propsfile": 'C:\Users\pihltd\Documents\modeltest\cds-model-props.yml'
  "modelfile": 'C:\Users\pihltd\Documents\modeltest\cds-model.yml'
  "outputfile": 'C:\Users\pihltd\Documents\modeltest\ConfigOldOutput.csv'
"headers":
  "a": "DO NOT USE"
  "b": "Batch User"
  "c": "Batch Name"
  "d": "Seq ID"
  "e": "*Model Name"
  "f": "*Model ID"
  "g": "*Model Version"
  "h": "Element Long  Name"
  "i": "*Element Physical Name"
  "j": "Element Description"
  "k": "Element Type"
  "l": "Characteristic Long Name"
  "m": "*Characteristic Physical Name"
  "n": "Characteristic Order"
  "o": "Characteristic Description"
  "p": "Characteristic Type"
  "q": "Characteristic Min Length"
  "r": "Characteristic Max Length"
  "s": "Characteristic Data Type"
  "t": "Characteristic UOM"
  "u": "Characteristic Mandatory?"
  "v": "Characteristic PK?"
  "w": "Characteristic Default"
  "x": "CDE ID"
  "y": "CDE Version"
  "z": "Element Mapping Group"
  "aa": "Characteristic FK?"
  "ab": "FK Element Name"
  "ac": "FK Element Characteristic Name"
  "ad": "Comments"
