"modelinfo":
  "b": "pihl"
  "c": "CDS Batch 2"
  "e": "CDS Data Model"
  "g": "3.0.0"
  "k": "Node"
  "p": "Property"
"scriptinfo":
  "propsfile": "/home/pihl/models/cds-model/model-desc/cds-model-props.yml"
  "modelfile": "/home/pihl/models/cds-model/model-desc/cds-model.yml"
  "outputfile": "CDSDataModel_3_0_0_CodeMap.csv"
"headers":
  "a": "DO NOT USE"
  "b": "Batch User"
  "c": "Batch Name"
  "d": "Seq ID"
  "e": "*Model Name"
  "f": "*Model ID"
  "g": "*Model Version"
  "h": "Element Long  Name"
  "i": "*Element Physical Name"
  "j": "Element Description"
  "k": "Element Type"
  "l": "Characteristic Long Name"
  "m": "*Characteristic Physical Name"
  "n": "Characteristic Order"
  "o": "Characteristic Description"
  "p": "Characteristic Type"
  "q": "Characteristic Min Length"
  "r": "Characteristic Max Length"
  "s": "Characteristic Data Type"
  "t": "Characteristic UOM"
  "u": "Characteristic Mandatory?"
  "v": "Characteristic PK?"
  "w": "Characteristic Default"
  "x": "CDE ID"
  "y": "CDE Version"
  "z": "Element Mapping Group"
  "aa": "Characteristic FK?"
  "ab": "FK Element Name"
  "ac": "FK Element Characteristic Name"
  "ad": "Comments"
