"excelfile": 'C:\Users\pihltd\Documents\VMShare\CRDC Submission Model Custom Report_20241125.xlsx'
"worksheet": "CRDC SubModelCustomRpt_11252024"
"mdffile" : 'C:\Users\pihltd\Documents\modeltest\CRDC_Submission_20241125_MDF.yml'
"mdfprops" : 'C:\Users\pihltd\Documents\modeltest\CRDC_Submission_20241125_MDF_Props.yml'
"modelHandle": "CRDC_Submission"
"modelVersion": "0.2"