"excelfile": "/media/vmshare/CRDC Submission Model Custom Report_20240910.xlsx"
"worksheet": "CRDC Submission Model Rpt-0910"
"mdffile" : "/home/pihl/models/crdc/CRDC_Submission_MDF.yml"
"mdfprops" : "/home/pihl/models/crdc/CRDC_Submission_MDF_Props.yml"