"excelfile": "/home/pihl/models/crdc-search/CRDC_Search_Model_V1_1.xlsx"
"worksheet": "CRDC Common Model Report 012424"
"mdffile" : "/home/pihl/models/crdc-search/CRDC_Search_MDF.yml"
"mdfprops" : "/home/pihl/models/crdc-search/CRDC_Search_MDF_Props.yml"