"jsonschema" : 'C:\Users\pihltd\Documents\github\data-models\HTAN.model.jsonld'
"csvschema" : 'C:\Users\pihltd\Documents\github\data-models\HTAN.model.csv'
"mdf_model_file" : 'C:\Users\pihltd\Documents\modeltest\HTAN\HTAN.model.yml'
"mdf_props_file" : 'C:\Users\pihltd\Documents\modeltest\HTAN\HTAN.model_props.yml'