"htan_csv_file" : "/home/pihl/models/data-models/HTAN.model.csv"
"mdf_model_file" : "/home/pihl/models/data-models/HTAN_model.yml"
"mdf_model_props_file" : "/home/pihl/models/data-models/HTAN.model_props.yml"